NCSC-NL/OpenSSL-2022

software/README.md

Ubuntu 22.10 currently offers Openssl 3.0.5 and this can be vulnerable. Verified by locally checking out the container.
Signed-off-by: Nico Rikken <nico.rikken@alliander.com>

Add Ubuntu 22.10

---

software/README.md

NodeJS 16/17 doesn't use OpenSSL 3
NodeJS 18 and 19 do use OpenSSL 3.0, added investigation link

Updates for NodeJS

---

software/README.md

Updated Ubiquiti links to the official statement of Ubiquiti instead of the community forum

Update Ubiquiti links

---

software/README.md

Added Tenable Nessus Network Monitor 6.1.0
Other Tenable products are possibly vulnerable too.

Add Tenable Nessus Network Monitor 6.1.0

---

software/README.md

The list didn't specify the Red Hat UBI images older than 9.0. This PR fixes that.

Add Red Hat - Universal Base Images < v9.0

---

software/README.md

In addition to PR #59, I fixed the mentioned OpenSSL version to what is specified in the [documentation](https://access.redhat.com/security/vulnerabilities/RHSB-2022-004) and added the same clarification for RHEL <=8.

Fixed UBI 8 OpenSSL version and added RHEL <= 8

---

software/README.md

Add Node.js 17. It's missing from vendor's blog post, but a member of the Node.js security team told me it was deliberately omitted since it's EOL and won't be receiving an update. Their blog post describes their pending updates, not which versions are vulnerable.
Changelog indicates all of 17.x uses OpenSSL 3.0 https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V17.md#17.0.0
- X ] Version: Status Vulnerable / Workaround? -> List vulnerable versions.

Add Node.js 17 - Investigation

---

software/README.md

12.1.0 is also confirmed vulnerable (running 3.0.3.0, observed in our environment)
statement not available, found in local environment

Added vmware tools version 12.1

---

software/README.md

With CVE disclosure, Code42 Incydr status is now Not vuln rather than Investigation. 
Current status is reflected on the [industry response page](https://support.code42.com/Terms_and_conditions/Code42_customer_support_resources/Code42_response_to_industry_security_incidents).

Update Code42 status to Not vuln

---

software/README.md

I am not sure how to reflect the optionally available OpenSSL 3.0.1 properly, thus I just gave it a try.
Note: I am _not_ a SUSE employee.

Add SUSE/Enterprise Linux Server

---

software/README.md

Packages in EPEL (or other 3rd party packages) might rely on the additionally provided OpenSSL version in EPEL.
* EPEL 8 provides optionally OpenSSL from RHEL 9
* EPEL 7 provides optionally OpenSSL from RHEL 8
Whether an EPEL package relies on OpenSSL from RHEL or on EPEL is up to the specific EPEL package and EPEL packager.

Add Fedora/EPEL

---

software/README.md

Basically the same like RHEL and EPEL, except that Oracle mixes them in their repositories.

Add Oracle/Linux

---

software/README.md

The fix is in the current compose that's being pushed out to mirrors:
https://composes.stream.centos.org/production/CentOS-Stream-9-20221101.0/compose/BaseOS/x86_64/os/Packages/
https://composes.stream.centos.org/production/CentOS-Stream-9-20221101.0/compose/BaseOS/aarch64/os/Packages/
https://composes.stream.centos.org/production/CentOS-Stream-9-20221101.0/compose/BaseOS/ppc64le/os/Packages/
https://composes.stream.centos.org/production/CentOS-Stream-9-20221101.0/compose/BaseOS/s390x/os/Packages/
Signed-off-by: Michel Alexandre Salim <salimma@centosproject.org>
Alternatively, include and link a file in the …

Mark CentOS Stream 9 as fixed

---

software/README.md

CentOS, RHEL, Rocky Linux and AlmaLinux 9 are forks and/or clones/derivates of each other, thus using a consistent version string for all of them makes sense to me.

Ensure same fixed version string for CentOS like for RHEL/derivates

---

software/README.md

I wasn't able to find a real statement, just a forum post. As they claim to be FreeBSD-based ([which ships OpenSSL 3](https://wiki.freebsd.org/OpenSSL) meanwhile), it might needs to be double-checked.

Add Netgate/pfSense

---

scanning/README.md

removes extra backtick so command can be copied and pasted

Remove extra backtick

---

software/README.md

WithSecure, previously known as F-Secure. Their Linux Security 64 seems to bundle OpenSSL according to older changelogs, however it is unclear to me which version etc. I'm following up with them privately using a business ticket tomorrow.
Note: The “64” refers to 64 bit, not to a version number.

Add WithSecure/Linux Security 64

---

software/README.md

Ref highlight:
https://jfrog.com/knowledge-base/upcoming-openssl-3-x-critical-vulnerability/#:~:text=the%20jfrog%20platform%20is%20not%20vulnerable%20to%20this%20issue%20since%20it%20does%20not%20use%20openssl%203.x.

add JFrog all (not vuln)

---

software/README.md

Ref text:
https://www.mend.io/resources/blog/advisory-new-openssl-critical-security-vulnerability/#:~:text=therefore%2C%20mend%20is%20not%20impacted%20by%20this%20vulnerability.

Add Mend (all) - not vuln

---

software/README.md

Ref text:
https://support.cpanel.net/hc/en-us/articles/4416312844055-Is-cPanel-affected-by-OpenSSL-Security-Advisory-CVE-2021-4044-#:~:text=cpanel%20servers%20don't%20use%20openssl%20version%203

Add cPanel (all) - not vuln

---

software/README.md

OpenSSL is a ClamAV dependency and the ClamAV binaries provided by Cisco on the regular ClamAV website are statically linked against a bundled OpenSSL (unknown version), at least for Linux I've been able to verify this:
```
wget https://www.clamav.net/downloads/production/clamav-0.105.1-2.linux.x86_64.rpm
rpm2cpio clamav-0.105.1-2.linux.x86_64.rpm | cpio -idm  # Extract RPM
strings usr/local/lib64/libclamav.so.9.1.0 | grep -i openssl  # OpenSSL matches
ldd usr/local/lib64/libclamav.so.9.1.0  # Not linked against libcrypto/libssl
```
I'm however unsure how to verify for Mac and Windows, but I guess these aren't built using much different options in general.
Some pointers to get it merged quickly: …

Add Cisco/ClamAV

---

software/README.md

"Zerto is only using OpenSSL 1.1.1, and as such, is not affected."

Add Zerto (not vuln)

---

software/README.md

The maintainers finally pushed a new build to Dockerhub. As the build does a `apt full-upgrade` this vuln is now fixed (confirmed locally)

Update Ubuntu Squid as Fix
