NCSC-NL/OpenSSL-2022

software/README.md

brand: JavaScript

---

software/README.md

FreeBSD as base for OPNSense and pfSense CE are might be interesting.

Add FreeBSD

---

software/README.md

Add Ubuntu

---

software/README.md

Add Alpine/Alpine Linux

---

software/README.md

Add Ubiquiti/UniFi

---

scanning/README.md

Added blogpost from Microsoft to scanning/readme.

Added Microsoft Defender for Cloud for scanning

---

software/README.md

Clarifications on NetBSD (different versions in different releases, added pkgsrc) and noting NodeJS 17.x (albeit EOL).

NetBSD and Nodejs corrections

---

scanning/README.md

M365 Defender and Azure Sentinel KQL query to detect OpenSSL installations on devices with version 3.0*

KQL Detection vulnerable OpenSSL version

---

software/README.md

Added Cisco 

---

scanning/README.md

OSquery for Linux systems addition for scanning

---

software/README.md

Updated link to affectedness statement to Red Hat Security Bulletin pertinent to this issue.

Red Hat: Updated affectedness link statement

---

software/README.md

Add VMware Photon OS

---

software/README.md

Status: Not vuln, all versions <= 3.8.2beta07 support OpenSSL 1.1.1
Link: https://tunnelblick.net/cRlsNotes.html
I did mind the sorting!

Add Tunnelblick

---

software/README.md

Add NixOS 22.05 and unstable

---

software/README.md

Add IBM/Pre-announcement

---

software/README.md

Add F5 Networks (BIG-IP, BIG-IQ, NGINX, Traffix)

---

software/README.md

Add Proxmox 7 as not affected

---

software/README.md

add Amazon Linux 2 and 2022

---

scanning/README.md

Add table with external sources

---

scanning/README.md

I've added the Splunk regex and query to assist in the investigation

Add Splunk query

---

software/README.md

Updated: Intel/Queencreek

---

software/README.md

Added VMware Tools 12.0.0

---

software/README.md

Add Trellix EPO

---

software/README.md

Added Tenable/ Nessus 10.3.0 Vulnerable

Add Tenable/ Nessus 10.3.0 Vulnerable

---

scanning/README.md

Linux scanning capabilities external source

---

software/README.md

Added Docker-Image Ubuntu Suqid:
https://hub.docker.com/r/ubuntu/squid
OpenSSL-Version: 3.0.5 5

Add ubuntu/squid

---

software/README.md

ubi9 is used by developers to base their delivered software upon, as such ubi9 based apps are vulnerable.

redhat / OpenShift 4 + ubi9 notes

---

software/README.md

Update Ubiquiti/All Products

---

scanning/README.md

MacOS OSQuery added

---

software/README.md

Add Bitdefender products

---

software/README.md

Add Broadcom Symactec Endpoint Protection Products

---

software/README.md

Adds Harbor

---

software/README.md

Added AsusWRT

---

scanning/README.md

MacOS: Checking homebrew packages without OSQuery

---

README.md

Add Openssl Release notification link

Add Openssl Release notification reference

---

README.md

- Add CVE reference
- Add Openssl security advisory

Add Openssl security alert reference

---

software/README.md

Added Nasuni products and a link to their official statement.

Add Nasuni products

---

software/README.md

PR updates Ubuntu package URLs to filter for specific release version. 

Update Ubuntu package urls

---

software/README.md

Added new info from https://support.f5.com/csp/article/K44030142

Updated F5 Networks/Multiple

---

software/README.md

Fixed to sorting of software/readme.md. This makes is easier to find specific software. Sorry that at least one of the entries that was not correct, was mine :)

Fixed sorting in software

---

software/README.md

Vendor statement on Twitter-account, see https://nlnetlabs.nl/projects/rpki/krill/

Add NLnet Labs/Krill

---

software/README.md

Add Juniper/JunOS

---

software/README.md

- [ x] PR Title: Please use "Add <vendor/product name>" (instead of "Update README.md")
- [ x] Status: please select a value from the status table at the top
- [ x] Version: Status Vulnerable / Workaround? -> List vulnerable versions.
- [ x] Links: make sure you link to a public statement by the developer.
- [ x] Please mind the sorting

Add Homebrew/Brew

---

software/README.md

- [X ] PR Title: Please use "Add <vendor/product name>" (instead of "Update README.md")
- [ X] Status: please select a value from the status table at the top
- [X ] Version: Status Vulnerable / Workaround? -> List vulnerable versions.
- [X ] Links: make sure you link to a public statement by the developer.
- [X ] Please mind the sorting

Updated Juniper/JunOS Evolved

---

software/README.md

- [ x] PR Title: Please use "Add <vendor/product name>" (instead of "Update README.md")
- [x ] Status: please select a value from the status table at the top
- [ x] Version: Status Vulnerable / Workaround? -> List vulnerable versions.
- [ x] Links: make sure you link to a public statement by the developer.
- [x ] Please mind the sorting

Updated Red Hat / Enterprise Linux as Fixed

---

software/README.md

Add Check Point reference article

Add Check Point

---

software/README.md

Synacor's Zimbra Email & Collaboration bundles OpenSSL

Add Synacor/Zimbra Email & Collaboration

---

software/README.md

Add Univention/Corporate Server

---

software/README.md

Open source base for (commercial) Huawei EulerOS

Add Huawei/openEuler

---

software/README.md

- [x ] PR Title: Please use "Add <vendor/product name>" (instead of "Update README.md")
- [x ] Status: please select a value from the status table at the top
- [x ] Version: Status Vulnerable / Workaround? -> List vulnerable versions.
- [ x] Links: make sure you link to a public statement by the developer.
- [ x] Please mind the sorting

Updated Rocky Linux Fixed

---

software/README.md

- [x ] PR Title: Please use "Add <vendor/product name>" (instead of "Update README.md")
- [x ] Status: please select a value from the status table at the top
- [x ] Version: Status Vulnerable / Workaround? -> List vulnerable versions.
- [x ] Links: make sure you link to a public statement by the developer.
- [x ] Please mind the sorting

Updated Fedora Rawhide fixed

---

software/README.md

- [ x] PR Title: Please use "Add <vendor/product name>" (instead of "Update README.md")
- [x ] Status: please select a value from the status table at the top
- [x ] Version: Status Vulnerable / Workaround? -> List vulnerable versions.
- [x ] Links: make sure you link to a public statement by the developer.
- [ x] Please mind the sorting

Updated AlmaLinux Fixed

---

software/README.md

Add EuroLinux/EuroLinux

---

software/README.md

- [x ] PR Title: Please use "Add <vendor/product name>" (instead of "Update README.md")
- [ x] Status: please select a value from the status table at the top
- [ x] Version: Status Vulnerable / Workaround? -> List vulnerable versions.
- [ x] Links: make sure you link to a public statement by the developer.
- [ x] Please mind the sorting

Updated HashiCorp Not vuln

---

software/README.md

Add Aruba - All product not vuln

---

software/README.md

Acronis products are not affected. Link provided.

Add Acronis - All products not vuln

---

software/README.md

Updated Cisco

---

software/README.md

Add IBM WebSphere App Server/Liberty/HTTP Server

---

software/README.md

Add Arista/All products

---

software/README.md

Updated Tenable with official statement

---

software/README.md

https://packages.fedoraproject.org/pkgs/openssl/openssl/
https://bodhi.fedoraproject.org/updates/FEDORA-2022-0f1d2e0537
https://bodhi.fedoraproject.org/updates/FEDORA-2022-502f096dce

Update Fedora 36 + 37

---

software/README.md

Added Infoblox BloxOne, NetMRI and NIOS information

Add Infoblox BloxOne, NetMRI and NIOS

---

software/README.md

Add SonicWall
https://psirt.global.sonicwall.com/vuln-detail/SNWLID-2022-0023

Add SonicWall

---

software/README.md

Updated F5 products with OpenSSL versions where we have already completed analysis.

Update F5 products

---

software/README.md

Remove duplicate SonicWall entry

Remove duplicate SonicWall entry

---

software/README.md

Add Sophos Products

---

software/README.md

Add Synology Products

---

software/README.md

Updated Fortinet

---

software/README.md

Put Pulse Secure (Ivanti) on alphabetical order, added RSA (SecurID) authentication products.

Add RSA (SecurID) Products

---

software/README.md

Added ivanti

---

software/README.md

document [Argo CD](https://argo-cd.readthedocs.io/en/stable/) as fixed since there are updated container images available.

Add Argo Project/Argo CD

---

software/README.md

Add Splunk (enterprise-wide) - not vuln

---

software/README.md

add Cloudflare (all)

---

software/README.md

Add DigiCert (all) - not vuln

---

software/README.md

[Added MacPorts command-line snip](https://github.com/NCSC-NL/OpenSSL-2022/commit/e328e38d4f5649c7f98d7453144b77c6e810edea)

Added MacPorts command-line snip

---

software/README.md

Add Governikus Ausweis 2

---

software/README.md

Ref text: https://www.telerik.com/blogs/openssl-vulnerability-what-you-need-know#:~:text=our%20products%20are%20not%20using%20the%20impacted%20version%20of%20openssl

add Telerik: not vuln (all)

---

software/README.md

only security concerns regarding the cves

Add GitLab B.V./GitLab

---

software/README.md

Update Mageia Fix

---

software/README.md

This adds the two products Confluence and Jira from Atlassian to the list

add Atlassian Confluence and Atlassian Jira

---

software/README.md

Updated Red Hat UBI9 fixed

---

software/README.md

Updated NodeJS with vendor statement (vulnerable)

---

software/README.md

Updated F5/Nginx (all products)

---

software/README.md

Ref text:
https://discuss.elastic.co/t/elastic-security-statement-for-openssl-cve-2022-3786-and-cve-2022-3602-openssl-version-3-0-7/318039#:~:text=5h-,elastic%20products%20are%20not%20affected%20by%20this%20issue.,-On%20Oct%2025

Add Elastic (all) - not vuln

---

software/README.md

This adds the Atlassian Bitbucket products and sorts the Atlassian rows.  Although Atlassian has confirmed their Docker images are impacted, there has been no specific information posted so I've left the status as `Investigation`.
---

Add Atlassian Bitbucket

---

software/README.md

Updated Offensive Security/Kali Fix

---

software/README.md

Wasn't sure how to express the "uses OS OpenSSL" - let me know, or feel free to edit!

Add Icinga (WIn: not vuln; Linux: uses OS OpenSSL)

---

software/README.md

Updated Trend Micro

---

software/README.md

Update Cisco (2 vulnerable products)

---

software/README.md

Update existing product and add missing products clarified by vendor using security advisory.

Update SUSE/* as fixed

---

software/README.md

Add curl & keepassxc

---

software/README.md

Update nodejs fix

---

software/README.md

Add Lacework Linux Agent Docker Image

---

software/README.md

Updated Trend Micro product list on 11/8/2022

Updated Trend Micro affected list 11/8/2022

---

software/README.md

Updated Debian 12

---

software/README.md

Updated EuroLinux

---

software/README.md

Updated Veritas

---

software/README.md

Fix spacing VMWare
